# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

sudo: required

services:
  - redis-server

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libhiredis-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package ropensci/RedisAPI
  - ./travis-tool.sh github_package richfitz/RedisHeartbeat

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: n9tUe5APG2KTy6KRz6GA6YSCte8tc77TuOKo2sSnnKhdYFFl9wPQ9heuS2JPldpNMB0dmgCsqDuPIiKh8yuKnKQWqSOWiIlkz0vdNthWE
